from setuptools import setup

setup(
    name="rays-core",
    version="1.0.0",
    description="RAYS-CORE — AI-Powered Development Assistant",
    author="Samreedh Bhuyan",
    url="https://github.com/<your-username>/RAYS-CORE",
    py_modules=[
        "rays_main",
        "rays_ui",
        "rays_generator",
        "ai_client",
        "chunk_generator",
        "code_executor",
        "code_generator",
        "indexing",
        "symbol_detection",
        "task_analyzer",
        "terminal_engine",
        "planning",
        "permission",
        "new_codebase_generator",
        "anchoring",
        "execution",
        "memory",
        "file_skeleton",
        "file_anchor",
        "file_analyzer",
        "symbol_anchor",
        "chat_context_pipeline",
        "git_status_summarizer",
        "affected_symbols_skeleton_fill",
    ],
    install_requires=[
        "rich",
        "requests",
        "pyyaml",
        "msgpack",
        "chromadb",
        "tree-sitter",
    ],
    entry_points={
        "console_scripts": [
            "rays=rays_main:main",
        ],
    },
    python_requires=">=3.10",
)
